---
title: "Longitudinal (Generalized Least Squares) Train"
author: "Jiaxing Joy Qiu"
date: "4/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "~/Documents/BSI/code/Transplant")
knitr::opts_chunk$set(error=TRUE,        # Keep compiling upon error
                      collapse=FALSE,    # collapse by default
                      echo=FALSE,         # echo code by default
                      comment = "#>",    # change comment character
                      fig.dim = c(10,3),     # set figure width
                      out.width = "100%", # set width of displayed images
                      warning=FALSE,     # do not show R warnings
                      message=FALSE,
                      result='asis')     # do not show R messages

```

```{r}
# --- prepare suitable dataset for this task  ----
source("./prepare/prep_raw.R")
# --- prepare global functions ----
source("./prepare/functions.R")
```

```{r}
# --- prepare local functions and packages ----
require(rms)
require(nlme)
# ---- prepare feature names ----
features <- c('Temp', 
              'Resp', 
              'Pulse', 
              'SBP', 
              'DBP', 
              #'SpO2',
              #'GCS', 
              #'FiO2', 
              #'O2_Flow', 
              #'GLUCOSE', 
              #'TOTAL_BILIRUBIN', 
              'POTASSIUM',
              'ALBUMIN', 
              'CALCIUM', 
              'SODIUM', 
              'WHITE_BLOOD_CELL_COUNT', 
              'PHOSPHORUS',
              #'PROTIME_INR', 
              #'CREATININE', 
              'PLATELET_COUNT', 
              #'ALT_GPT', 
              'CO2',
              #'ALKALINE_PHOSPHATASE', 
              #'AST_GOT', 
              'PCO2', 
              'CHLORIDE', 
              #'TROPONIN_I',
              #'PARTIAL_THROMBOPLASTIN_TIME', 
              #'LACTIC_ACID', 
              'BLOOD_UREA_NITROGEN',
              #'OXYGEN_SATURATION', 
              'MAGNESIUM'#, 
              #'FIO2'
              )
# ---- prepare task data ----
data <- bind_rows(df_ep_raw, df_safe_window_raw)
data$group <- as.factor(data$group)
data$ep_id <- as.factor(data$ep_id)
data$time_idx <- as.numeric(data$relative_time - min(data$relative_time) +1) # start 1 step 1 time index ##### don't name variable 'time'
```


```{r}
# ---- select columns ----
for (fea in features){
  df_mdl <- data[, c(fea, 'time_idx', 'group', 'ep_id')]
  df_mdl$y <- df_mdl[,fea]
  
  # ---- prepare modeling data ----
  df_mdl <- upData(df_mdl,
                   keep=c('y','time_idx','group','ep_id'),
                   labels=c(y = fea,
                            time_idx = "time index [-24h, 24h]",
                            group = "primary groups",
                            ep_id = "episode id"),
                   units= c(time_idx = "15 mins"),
                   print=FALSE)
  html(contents(df_mdl), sortlevels=TRUE, nshow=FALSE, prlevels=FALSE)
  dd <- datadist(df_mdl); options(datadist='dd')
  
  
  # ---- fit model ----
  fml <- formula("y ~ rcs(time_idx, 5) * catg(group)")
  mdl <- Gls(fml, #y ~ rcs(time_idx, 5) * catg(group), 
             data=df_mdl,
             x=TRUE,
             correlation = corCAR1(form = ~ time_idx | catg(ep_id)),
             method="ML")
  save(mdl, file = paste0("./task_longitudinal_mdl/gls/gls_mdl_obj/",fea,"_mdl.rda") )
}


```
